name: CI - build and test

on:                                
  push:
    branches: [ main ]

jobs:
  build:                           

    runs-on: ubuntu-latest         

    steps:    
    env: {{secrets.REPORTS_SSH_KEY}}
    	secret:   
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2        
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew              
    - name: Build and test
      run: ./gradlew build | 
           ./gradlew test
    - name: Deploy reports
      run: |
      ssh-agent
      ssh-add <(echo "$secret")
      git config --global user.email "arapc001@odu.edu"
      git config --global user.name "Project Actions"
      ./gradlew deployReports